name: Deploy to Railway and Netlify

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Build Docker + Deploy on Railway
    runs-on: ubuntu-latest   # ← Obligatoire
    steps:
      # Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Construire l'image Docker
      - name: Build Docker image
        run: docker build -t my-backend .

      # Installer Railway CLI
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      # Authentifier Railway avec ton token secret
      - name: Authenticate Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway login --token $RAILWAY_API_TOKEN

      # Déployer le backend
      - name: Deploy to Railway
        run: railway up --detach

  frontend:
    name: Deploy on Netlify
    runs-on: ubuntu-latest
    steps:
      # Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Installer les dépendances
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      # Construire le projet frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      # Déployer sur Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install -g netlify-cli
          netlify deploy --dir=./frontend/dist --prod --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
